import { describe, expect, it } from 'vitest'
import type { DocEntry, DocManifest, DocWing, SearchIndex } from './content.ts'
import {
  groupFor,
  neighbours,
  opensEveryGroup,
  pagesOf,
  parentOf,
  wingFor,
} from './docsNav.ts'
import { searchDocs, tokenize } from './search.ts'

/*
 * The two pure halves of the reading room: where a route sits, and what a query
 * finds.
 *
 * Relevance is the thing here that degrades silently. A ranking change breaks
 * nothing, throws nothing and renders identically — the results are simply
 * worse, one edit at a time, and nobody notices until searching the
 * documentation stops being how anyone uses it. So the ranking is asserted as
 * *order*, on a fixture small enough to reason about, rather than as scores.
 *
 * Against a fixture rather than the real index, deliberately: the real one is
 * generated by `pnpm docs:build` into a gitignored directory, and `pnpm test` runs
 * before the build that writes it. A test that passed only after a build would
 * be a test that is skipped in exactly the checkout that most needs it.
 */

const wing = (
  id: string,
  home: string,
  groups: DocWing['groups'],
): DocWing => ({
  id,
  label: id,
  blurb: `the ${id} wing`,
  framing: { address: 's:SOL/b:2', phase: -135, tilt: -30, fill: 2.2 },
  home,
  groups,
})

const entry = (title: string, wingId: string): DocEntry => ({
  title,
  label: title,
  wing: wingId,
  kind: 'prose',
  asset: `${title.toLowerCase()}-00000.json`,
})

const MANIFEST: DocManifest = {
  version: 'test',
  wings: [
    wing('start', '/docs', [
      { label: null, head: null, pages: ['/docs', '/docs/vision'] },
    ]),
    wing('concepts', '/docs/concepts/frames', [
      {
        label: 'Mechanisms',
        head: null,
        pages: ['/docs/concepts/frames', '/docs/concepts/time'],
      },
      { label: 'Records', head: '/docs/adr', pages: ['/docs/adr/0001'] },
    ]),
    wing('api', '/docs/api', [
      {
        label: 'spatial',
        head: '/docs/api/spatial',
        pages: ['/docs/api/spatial/Sector'],
      },
    ]),
  ],
  pages: {
    '/docs': entry('Documentation', 'start'),
    '/docs/vision': entry('Vision', 'start'),
    '/docs/concepts/frames': entry('Reference frames', 'concepts'),
    '/docs/concepts/time': entry('Simulation time', 'concepts'),
    '/docs/adr': entry('Records', 'concepts'),
    '/docs/adr/0001': entry('Universe coordinates', 'concepts'),
    '/docs/api': entry('Reference', 'api'),
    '/docs/api/spatial': entry('spatial', 'api'),
    '/docs/api/spatial/Sector': entry('Sector', 'api'),
  },
  counts: {
    pages: 9,
    documents: 6,
    words: 100,
    diagrams: 1,
    packages: 1,
    exports: 1,
  },
}

describe('where a route sits', () => {
  it('finds the wing that lists it', () => {
    expect(wingFor(MANIFEST, '/docs/concepts/time')?.id).toBe('concepts')
    expect(wingFor(MANIFEST, '/docs/api/spatial/Sector')?.id).toBe('api')
  })

  /* A link written against a symbol that has since been renamed. The masthead
     still needs a framing to draw while the article says what went wrong. */
  it('guesses the reference for an unknown page under it', () => {
    expect(wingFor(MANIFEST, '/docs/api/spatial/Gone')?.id).toBe('api')
    expect(wingFor(MANIFEST, '/docs/nowhere')?.id).toBe('start')
  })

  it('finds the group, whether the route is in it or heads it', () => {
    expect(
      groupFor(wingFor(MANIFEST, '/docs/adr/0001'), '/docs/adr/0001')?.label,
    ).toBe('Records')
    expect(groupFor(wingFor(MANIFEST, '/docs/adr'), '/docs/adr')?.label).toBe(
      'Records',
    )
  })

  it('names the page a member is read inside, and nothing above it', () => {
    expect(
      parentOf(
        wingFor(MANIFEST, '/docs/api/spatial/Sector'),
        '/docs/api/spatial/Sector',
      ),
    ).toBe('/docs/api/spatial')
    // A group's own head has no parent: it *is* the parent.
    expect(
      parentOf(wingFor(MANIFEST, '/docs/api/spatial'), '/docs/api/spatial'),
    ).toBeNull()
  })

  it('puts a group head in front of its pages when reading a wing', () => {
    expect(pagesOf(MANIFEST.wings[1] as DocWing)).toEqual([
      '/docs/concepts/frames',
      '/docs/concepts/time',
      '/docs/adr',
      '/docs/adr/0001',
    ])
  })
})

describe('previous and next', () => {
  it('walks the wing in reading order', () => {
    expect(neighbours(MANIFEST, '/docs/concepts/time')).toEqual({
      previous: '/docs/concepts/frames',
      next: '/docs/adr',
    })
  })

  /*
   * Running off the end of one wing into the next is not the next thing anybody
   * wanted: the wings are four different reasons to be reading, and a pair of
   * arrows that quietly changes the subject is worse than a pair that stops.
   */
  it('stops at the end of a wing rather than crossing into another', () => {
    expect(neighbours(MANIFEST, '/docs/adr/0001').next).toBeNull()
    expect(neighbours(MANIFEST, '/docs').previous).toBeNull()
  })
})

describe('how much of a wing opens at once', () => {
  it('opens a short wing whole and leaves a long one to the current group', () => {
    expect(opensEveryGroup(MANIFEST.wings[1] as DocWing)).toBe(true)
    const huge = wing('big', '/docs/big', [
      {
        label: 'all',
        head: null,
        pages: Array.from({ length: 60 }, (_, at) => `/docs/big/${at}`),
      },
    ])
    expect(opensEveryGroup(huge)).toBe(false)
  })
})

/* ------------------------------------------------------------------------- */
/* Search                                                                     */
/* ------------------------------------------------------------------------- */

const INDEX: SearchIndex = {
  version: 'test',
  stop: ['the', 'and', 'for'],
  rows: [
    {
      r: '/docs/concepts/frames',
      t: 'Reference frames',
      w: 'concepts',
      k: 'prose',
      l: 'What does "3 m above the pad" mean while the planet orbits?',
      h: [
        ['surface-frames', 'Surface frames and the identity trap'],
        ['the-chain', 'The frame chain'],
      ],
      b: 'above chain frame frames identity orbit pad planet surface trap',
    },
    {
      r: '/docs/concepts/time',
      t: 'Simulation time',
      w: 'concepts',
      k: 'prose',
      l: 'Why 144 Hz produces the same universe as 60 Hz.',
      h: [['the-tick', 'The tick']],
      b: 'clock frame hertz simulation tick time universe',
    },
    {
      r: '/docs/api/spatial/Sector',
      t: 'Sector',
      w: 'api',
      k: 'api-member',
      l: 'One cell of the universe grid.',
      h: [],
      b: 'cell frame grid sector universe',
    },
  ],
}

describe('search', () => {
  it('ignores a term too short to locate anything', () => {
    expect(tokenize('a b')).toEqual([])
    expect(searchDocs(INDEX, 'a')).toEqual([])
  })

  /*
   * The `AND` makes a stop word poison: it is in no page's vocabulary, so a
   * query keeping one requires a term nothing can satisfy. "The frame chain"
   * returned nothing before the index started shipping its own list.
   */
  it('drops the words the index dropped, rather than failing on them', () => {
    expect(tokenize('the frame', INDEX.stop)).toEqual(['frame'])
    expect(searchDocs(INDEX, 'the frame').length).toBeGreaterThan(0)
  })

  it('ranks a title hit above a heading hit above a body hit', () => {
    const hits = searchDocs(INDEX, 'frame')
    expect(hits.map((hit) => hit.title)).toEqual([
      'Reference frames',
      'Simulation time',
      'Sector',
    ])
  })

  /* An `OR` would bury the page about both under every page that mentions
     either, which is the whole reason somebody typed two words. */
  it('requires every term, not any of them', () => {
    expect(searchDocs(INDEX, 'frame trap').map((hit) => hit.title)).toEqual([
      'Reference frames',
    ])
    expect(searchDocs(INDEX, 'frame unicorn')).toEqual([])
  })

  it('links to the section that matched rather than to the top of the page', () => {
    const [hit] = searchDocs(INDEX, 'identity')
    expect(hit?.route).toBe('/docs/concepts/frames#surface-frames')
    expect(hit?.section?.text).toBe('Surface frames and the identity trap')
  })

  it('has no section to offer when the title alone matched', () => {
    const [hit] = searchDocs(INDEX, 'sector')
    expect(hit?.route).toBe('/docs/api/spatial/Sector')
    expect(hit?.section).toBeNull()
  })

  /*
   * The one thing the index cannot represent is adjacency: it knows both words
   * occur on a page, not that they occur together. The raw query still can, and
   * this is where that is spent.
   */
  it('prefers a page whose title is the phrase', () => {
    const hits = searchDocs(INDEX, 'simulation time')
    expect(hits[0]?.title).toBe('Simulation time')
  })

  it('matches the start of a word, not the middle of one', () => {
    expect(searchDocs(INDEX, 'clo').map((hit) => hit.title)).toEqual([
      'Simulation time',
    ])
    expect(searchDocs(INDEX, 'ock')).toEqual([])
  })

  it('honours the limit', () => {
    expect(searchDocs(INDEX, 'frame', 2)).toHaveLength(2)
  })
})
