#!/usr/bin/env node
/*
 * Everything the brand is made of, from one drawing.
 *
 *     pnpm brand           re-render every artifact
 *     pnpm brand --check   fail if any of them has drifted from the source
 *
 * `design/brand/brandmark.svg` is the mark, and `design/brand/og-plate.png` is
 * one captured frame of the renderer that the share card's type sits on — see
 * `og.mjs` for why the card's background is a committed file rather than
 * either a drawing or a screenshot taken at build time. This script is the only
 * thing that reads either of them, and it writes the eight places the mark, the
 * name and the site's own description end up:
 *
 *     apps/game/public/favicon.svg           the mark on its slate-950 plate
 *     apps/game/public/favicon.ico           for clients that still ask
 *     apps/game/public/apple-touch-icon.png  iOS home screen, 180
 *     apps/game/public/icon-192.png          the PWA icon
 *     apps/game/public/icon-512.png          ...and the splash size
 *     apps/game/public/icon-maskable-512.png ...and the one Android crops
 *     apps/game/public/og.png                the share card
 *     apps/game/public/manifest.webmanifest  the install manifest
 *     apps/game/public/robots.txt            + sitemap.xml
 *     apps/game/src/icons/brandmark.ts       the paths, for <Logomark>
 *
 * **Why a generator and not ten hand-kept files.** There were three copies of
 * this mark before it: the component, the favicon, and the plate's fit
 * expressed as a magic transform in a comment. Three copies of a drawing is a
 * drawing that is about to be two drawings — and the moment it is, the tab, the
 * home screen and the running interface disagree about what the product looks
 * like, which is the one thing a mark exists to stop.
 *
 * **What `--check` does and does not cover.** It re-derives every *text*
 * artifact and diffs it, so a redrawn mark, a renamed page or a changed
 * description fails the gate. It does not diff the PNGs: `sharp`'s encoder is
 * not promised to be byte-stable across versions, so a dependency bump would
 * turn into a red gate that means nothing. It asserts they exist and are not
 * empty, and re-rendering them is one command.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { relative } from 'node:path'
import { format, getFileInfo, resolveConfig } from 'prettier'
import { PAGES, SITE, canonicalUrl } from '../../apps/game/src/site.ts'
import { checkPublicSurface } from './checkHead.mjs'
import { readMark, fit, markup, measure } from './mark.mjs'
import { composeOgCard, OG_HEIGHT, OG_PLATE, OG_WIDTH } from './og.mjs'

const ROOT = new URL('../../', import.meta.url)
const PUBLIC = new URL('apps/game/public/', ROOT)

const GENERATED = 'Generated by `pnpm brand`.'

/* ------------------------------------------------------------------------- */
/* The plate                                                                  */
/* ------------------------------------------------------------------------- */

/*
 * Two things a favicon has that the component does not, both because a tab
 * strip is not a surface this design system controls:
 *
 *   - a slate-950 plate, because half the platforms draw the strip white in
 *     light mode and an unbacked sky-blue mark vanishes into it
 *   - a 24-of-32 fit, which is the proportion at which a marque still reads as
 *     an icon rather than as a sticker with a margin
 *
 * `RADIUS` is 7 of 32 — the same 22% corner the platforms round a home-screen
 * icon to, so the drawn plate and the cropped one agree.
 */
const PLATE = { canvas: 32, size: 24, radius: 7 }

/**
 * Android crops a maskable icon to whatever shape the launcher likes, and only
 * the central 80% *circle* is promised to survive. 56% of the canvas is the
 * largest square that fits inside that circle with room for the shear.
 */
const MASKABLE = 0.56

/**
 * How much of a full-size icon the mark fills. 68%.
 *
 * Larger than the favicon's 24-of-32 (75%) *looks* like, and is not: a favicon
 * is 16 px of tab strip where a home-screen icon sits among others with visible
 * padding, so the same proportion reads as crowded there. Both the PWA icons
 * and the apple-touch icon use it; they differ only in the plate, which is
 * rounded for the former and square for the latter because iOS draws its own
 * corner and a second one inside it is a visible double bevel.
 */
const PLATE_FIT = 0.68

function plateSvg(
  mark,
  box,
  { canvas, size, radius, background = SITE.background },
) {
  const transform = fit(box, { canvas, size })
  const corner = radius === undefined ? '' : ` rx="${radius}"`
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${canvas} ${canvas}" width="${canvas}" height="${canvas}">
  <rect width="${canvas}" height="${canvas}"${corner} fill="${background}" />
  <g transform="${transform.attribute()}">
${markup(mark.paths, '    ')}
  </g>
</svg>
`
}

/* ------------------------------------------------------------------------- */
/* The text artifacts                                                         */
/* ------------------------------------------------------------------------- */

function faviconSvg(mark, box) {
  return `<!-- ${GENERATED} The mark is design/brand/brandmark.svg; edit that, not this. -->
${plateSvg(mark, box, PLATE)}`
}

function brandmarkModule(mark, box) {
  const paths = mark.paths
    .map(({ d, fill }) => `  { d: '${d}', fill: '${fill}' },`)
    .join('\n')
  const round = (value) => Number(value.toFixed(4))
  return `/*
 * ${GENERATED} The mark is design/brand/brandmark.svg.
 * Edit that file and run \`pnpm brand\`; \`pnpm brand --check\` guards this one.
 *
 * A generated module rather than an imported SVG so the mark is *markup* in the
 * tree: \`<Logomark>\` needs the three fills as separate paths to keep them on
 * the accent ramp rather than compositing an opacity fade, and an \`<img>\` of a
 * file cannot be styled or sized against the type it sits beside.
 */

export interface BrandmarkPath {
  readonly d: string
  readonly fill: string
}

export const BRANDMARK_VIEW_BOX = '${mark.view.x} ${mark.view.y} ${mark.view.width} ${mark.view.height}'

/** Brightest first: the accent ramp, sky-100 / sky-300 / sky-500. */
export const BRANDMARK_PATHS: readonly BrandmarkPath[] = [
${paths}
]

/**
 * Where the drawing actually sits inside its viewBox, measured rather than
 * declared — see \`scripts/brand/mark.mjs\`. Carried here so anything fitting
 * the mark into a box does not have to rasterize it to find out.
 */
export const BRANDMARK_BOX = {
  x: ${round(box.x)},
  y: ${round(box.y)},
  width: ${round(box.width)},
  height: ${round(box.height)},
} as const
`
}

function manifest() {
  /*
   * The install manifest.
   *
   * `display: standalone` rather than `fullscreen`: fullscreen takes the status
   * bar with it on Android, and this app already draws its own chrome over a
   * canvas — losing the clock and the battery to a HUD that has neither is a
   * bad trade for the 24 px it wins back.
   *
   * `id` is set explicitly and must never change. It is what the browser keys
   * an installed app on; leaving it implicit ties the identity to `start_url`,
   * so the first time a query parameter is added there the installed app
   * becomes a *second* app.
   */
  return `${JSON.stringify(
    {
      id: '/',
      name: SITE.name,
      short_name: SITE.name,
      description: SITE.description,
      start_url: '/',
      scope: '/',
      display: 'standalone',
      orientation: 'any',
      background_color: SITE.background,
      theme_color: SITE.background,
      categories: ['games', 'education', 'entertainment'],
      lang: 'en',
      dir: 'ltr',
      icons: [
        { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' },
        { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
        {
          src: '/icon-maskable-512.png',
          sizes: '512x512',
          type: 'image/png',
          purpose: 'maskable',
        },
      ],
      screenshots: [
        {
          src: SITE.socialImage,
          sizes: `${OG_WIDTH}x${OG_HEIGHT}`,
          type: 'image/png',
          form_factor: 'wide',
          label: `${SITE.name} — ${SITE.tagline}`,
        },
      ],
    },
    null,
    2,
  )}\n`
}

function robots() {
  /*
   * Open to everything, including the agents.
   *
   * A crawler that reads this project and answers a question about it is doing
   * the same job the documentation is, and there is nothing here to protect —
   * the source is Apache-2.0 and public. What is disallowed is the set of paths
   * that are not pages: an OAuth landing, and account stubs that render the
   * same "not in this build" panel and would otherwise be four ways to index
   * one non-feature.
   */
  const blocked = ['/auth/', '/profile', '/sign-in', '/sign-up']
  return `# ${SITE.name} — ${SITE.origin}
# ${GENERATED} The rules are in apps/game/src/site.ts.
#
# Everything is open, agents included. /llms.txt is the short version, written
# for a reader that is not a person, and the source is public:
# ${SITE.repository}

User-agent: *
${blocked.map((path) => `Disallow: ${path}`).join('\n')}
Allow: /

Sitemap: ${SITE.origin}/sitemap.xml
`
}

function sitemap() {
  /*
   * Deliberately just `<loc>`. `<changefreq>` and `<priority>` are ignored by
   * every major crawler, and `<lastmod>` would have to come from the wall clock
   * — a field that changes on every build and means nothing is worse than an
   * absent one, because a crawler that learns to distrust it distrusts the
   * whole file.
   */
  const urls = PAGES.filter((page) => page.index)
    .map((page) => `  <url><loc>${canonicalUrl(page.path)}</loc></url>`)
    .join('\n')
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${GENERATED} The list is PAGES in apps/game/src/site.ts. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`
}

/* ------------------------------------------------------------------------- */
/* ICO                                                                        */
/* ------------------------------------------------------------------------- */

/**
 * An ICO wrapping PNGs, which every browser since Vista reads.
 *
 * Written by hand because it is thirty bytes of header per image and the
 * alternative is a dependency whose whole job is those thirty bytes. `/favicon.ico`
 * is still the path a crawler, a feed reader and a bookmark importer ask for
 * without being told to, and a 404 there is a log line on every one of them.
 */
function ico(images) {
  const HEADER = 6
  const ENTRY = 16
  const header = Buffer.alloc(HEADER)
  header.writeUInt16LE(0, 0) // reserved
  header.writeUInt16LE(1, 2) // 1 = icon
  header.writeUInt16LE(images.length, 4)

  let offset = HEADER + ENTRY * images.length
  const entries = images.map(({ size, png }) => {
    const entry = Buffer.alloc(ENTRY)
    // 0 means 256 in this field, which is why it is a byte and why 256 works.
    entry.writeUInt8(size >= 256 ? 0 : size, 0)
    entry.writeUInt8(size >= 256 ? 0 : size, 1)
    entry.writeUInt8(0, 2) // palette size — none, this is truecolour
    entry.writeUInt8(0, 3) // reserved
    entry.writeUInt16LE(1, 4) // color planes
    entry.writeUInt16LE(32, 6) // bits per pixel
    entry.writeUInt32LE(png.length, 8)
    entry.writeUInt32LE(offset, 12)
    offset += png.length
    return entry
  })

  return Buffer.concat([header, ...entries, ...images.map(({ png }) => png)])
}

/* ------------------------------------------------------------------------- */
/* Driver                                                                     */
/* ------------------------------------------------------------------------- */

/**
 * Whatever Prettier would have written, for the files Prettier claims.
 *
 * Not tidiness — correctness of the gate. `pnpm check` runs both
 * `format:check` and `brand --check`, and without this the two disagree by
 * construction: `JSON.stringify(…, 2)` always expands an array where Prettier
 * collapses a short one, so every `pnpm format` broke the brand check and every
 * `pnpm brand` broke the format check. One of them had to yield, and it is this
 * one, because Prettier's opinion is the repository's.
 *
 * `getFileInfo` decides, rather than a list of extensions here: Prettier has no
 * parser for `.svg`, `.xml` or `.txt`, and asking it to format one throws.
 */
async function pretty(target, body) {
  const path = fileURLToPath(target)
  const { inferredParser } = await getFileInfo(path)
  if (inferredParser === null) return body
  return format(body, { ...(await resolveConfig(path)), filepath: path })
}

const say = (target, note) =>
  console.log(
    `  ${relative(fileURLToPath(ROOT), fileURLToPath(target))}${note === undefined ? '' : `  ${note}`}`,
  )

async function main() {
  const checking = process.argv.includes('--check')
  const mark = await readMark()
  const box = await measure(mark)

  const text = []
  for (const [target, body] of [
    [new URL('favicon.svg', PUBLIC), faviconSvg(mark, box)],
    [new URL('manifest.webmanifest', PUBLIC), manifest()],
    [new URL('robots.txt', PUBLIC), robots()],
    [new URL('sitemap.xml', PUBLIC), sitemap()],
    [
      new URL('icons/brandmark.ts', new URL('apps/game/src/', ROOT)),
      brandmarkModule(mark, box),
    ],
  ]) {
    text.push([target, await pretty(target, body)])
  }

  const binary = [
    'favicon.ico',
    'apple-touch-icon.png',
    'icon-192.png',
    'icon-512.png',
    'icon-maskable-512.png',
    'og.png',
  ].map((name) => new URL(name, PUBLIC))

  if (checking) {
    const stale = []
    for (const [target, wanted] of text) {
      const found = await readFile(target, 'utf8').catch(() => null)
      if (found !== wanted) stale.push({ target, missing: found === null })
    }
    for (const target of binary) {
      const found = await readFile(target).catch(() => null)
      if (found === null || found.length === 0)
        stale.push({ target, missing: true })
    }
    if (stale.length > 0) {
      console.error(
        'Brand artifacts have drifted from design/brand/brandmark.svg:',
      )
      for (const { target, missing } of stale) {
        console.error(
          `  - ${relative(fileURLToPath(ROOT), fileURLToPath(target))} ${missing ? 'is missing' : 'differs'}`,
        )
      }
      console.error('\nRun `pnpm brand` and commit the result.')
      process.exitCode = 1
      return
    }
    /*
     * The one artifact that is hand-kept rather than generated.
     *
     * Checked here rather than in a separate command because it belongs to the
     * same question — "does the public surface still say what `site.ts` says" —
     * and a second script is a second thing to remember to run. It cannot be
     * *fixed* by `pnpm brand`, so its failure names the tag rather than telling
     * anyone to re-run anything.
     */
    const surface = checkPublicSurface({
      html: await readFile(
        new URL('apps/game/astro/layouts/Base.astro', ROOT),
        'utf8',
      ),
      sw: await readFile(new URL('sw.js', PUBLIC), 'utf8'),
      publicFiles: new Set(await readdir(PUBLIC)),
    })
    if (surface.length > 0) {
      console.error('The static head disagrees with apps/game/src/site.ts:')
      for (const problem of surface) console.error(`  - ${problem}`)
      console.error(
        '\nEdit apps/game/astro/layouts/Base.astro to match, or src/site.ts if the head is right.',
      )
      process.exitCode = 1
      return
    }
    console.log('brand artifacts match design/brand/brandmark.svg')
    console.log('the document head and sw.js match apps/game/src/site.ts')
    return
  }

  console.log('Rendering from design/brand/brandmark.svg')
  for (const [target, body] of text) {
    await writeFile(target, body)
    say(target)
  }

  const { default: sharp } = await import('sharp')
  /** PNG from an SVG string at an exact pixel size. */
  const raster = async (svg, size) =>
    sharp(Buffer.from(svg), { density: 384 })
      .resize(size, size, { fit: 'contain', background: '#00000000' })
      .png({ compressionLevel: 9 })
      .toBuffer()

  const plate = plateSvg(mark, box, PLATE)
  const square = plateSvg(mark, box, {
    canvas: 512,
    size: 512 * PLATE_FIT,
    radius: 114,
  })
  const touch = plateSvg(mark, box, { canvas: 512, size: 512 * PLATE_FIT })
  const maskable = plateSvg(mark, box, { canvas: 512, size: 512 * MASKABLE })

  const icoSizes = [16, 32, 48]
  await writeFile(
    new URL('favicon.ico', PUBLIC),
    ico(
      await Promise.all(
        icoSizes.map(async (size) => ({
          size,
          png: await raster(plate, size),
        })),
      ),
    ),
  )
  say(new URL('favicon.ico', PUBLIC), `${icoSizes.join(', ')} px`)

  for (const [name, svg, size] of [
    ['apple-touch-icon.png', touch, 180],
    ['icon-192.png', square, 192],
    ['icon-512.png', square, 512],
    ['icon-maskable-512.png', maskable, 512],
  ]) {
    await writeFile(new URL(name, PUBLIC), await raster(svg, size))
    say(new URL(name, PUBLIC), `${size} px`)
  }

  /*
   * The share card: type over a captured frame, composited rather than drawn.
   *
   * `density: 96` renders the overlay at 4/3 scale and the resize takes it
   * back down, which is the only antialiasing the type gets — resvg has no
   * hinting and the 1 px rule under the lead would otherwise land on a half
   * pixel. The plate is already `OG_WIDTH x OG_HEIGHT`, so nothing resamples
   * the picture: whatever is committed is exactly what ships.
   */
  const card = await composeOgCard()
  const overlay = await sharp(Buffer.from(card), { density: 96 })
    .resize(OG_WIDTH, OG_HEIGHT)
    .png()
    .toBuffer()
  await writeFile(
    new URL('og.png', PUBLIC),
    await sharp(await readFile(OG_PLATE))
      .composite([{ input: overlay }])
      .png({ compressionLevel: 9 })
      .toBuffer(),
  )
  say(new URL('og.png', PUBLIC), `${OG_WIDTH}x${OG_HEIGHT}`)
}

await main()
