/*
 * Generated by `pnpm brand`. The mark is design/brand/brandmark.svg.
 * Edit that file and run `pnpm brand`; `pnpm brand --check` guards this one.
 *
 * A generated module rather than an imported SVG so the mark is *markup* in the
 * tree: `<Logomark>` needs the three fills as separate paths to keep them on
 * the accent ramp rather than compositing an opacity fade, and an `<img>` of a
 * file cannot be styled or sized against the type it sits beside.
 */

export interface BrandmarkPath {
  readonly d: string
  readonly fill: string
}

export const BRANDMARK_VIEW_BOX = '0 0 32 32'

/** Brightest first: the accent ramp, sky-100 / sky-300 / sky-500. */
export const BRANDMARK_PATHS: readonly BrandmarkPath[] = [
  { d: 'M12 2.5H30L25 9H7Z', fill: '#e0f2fe' },
  { d: 'M10 12.75H25.5L20.5 19.25H5Z', fill: '#7dd3fc' },
  { d: 'M8 23H21L16 29.5H3Z', fill: '#0ea5e9' },
]

/**
 * Where the drawing actually sits inside its viewBox, measured rather than
 * declared — see `scripts/brand/mark.mjs`. Carried here so anything fitting
 * the mark into a box does not have to rasterize it to find out.
 */
export const BRANDMARK_BOX = {
  x: 3,
  y: 2.5,
  width: 27,
  height: 27,
} as const
