import {
  ABOUT,
  CINEMA,
  DOCS,
  HOME,
  KEYS,
  PROFILE,
  SIGN_IN,
  SIGN_UP,
  AUTH_CALLBACK,
  PLANETARIUM,
  PLAY_MULTIPLAYER,
  PLAY_ONLINE,
  PLAY_SOLO,
  SETTINGS,
} from './pages/paths.ts'

/**
 * Identity and route metadata shared by Astro, browser navigation, analytics
 * and the brand generator. Node imports this file with type stripping, so it
 * cannot depend on browser globals or build-time environment replacement.
 */
export const SITE = {
  name: 'InertialRef',
  /** The canonical host. Everything else — a preview, a `workers.dev`
   *  fallback, localhost — is the same build wearing a different name, and
   *  neither analytics nor a canonical link should treat it as this site. */
  host: 'inertialref.app',
  origin: 'https://inertialref.app',
  tagline: 'A real sky, in a browser tab',
  /**
   * The one sentence a stranger gets, and the length is the constraint.
   *
   * Search results truncate a description around 160 characters on desktop and
   * nearer 120 on mobile; this lands at 157, so the clause that ends it is a
   * clause somebody chose rather than wherever Google's ellipsis fell.
   * `site.test.ts` holds every page to that bound.
   */
  description:
    'An open-source spaceflight simulator in a browser tab. The Milky Way is the real one — 7,123 cataloged systems within 150 light years, the rest from a seed.',
  author: 'Jon Jaques',
  repository: 'https://github.com/jonjaques/inertialref',
  licence: 'Apache-2.0',
  /** Slate-950. The page behind the app, the icon plate and the share card all
   *  sit on it, and a browser paints it before the bundle arrives. */
  background: '#020617',
  /** 1200x630, generated by `pnpm brand`. */
  socialImage: '/og.png',
} as const

/* ------------------------------------------------------------------------- */
/* Pages                                                                      */
/* ------------------------------------------------------------------------- */

export interface PageMeta {
  /** The path this describes. Matched as a prefix, longest first. */
  readonly path: string
  /**
   * The page's own name, in title case and without the product's.
   *
   * `documentTitle` appends the product. Written here the way it is written
   * everywhere else in this interface — a label is read by a screen reader and
   * copied into a bookmark, and neither of those can undo a shout.
   */
  readonly title: string
  readonly description: string
  /**
   * Whether it belongs in `sitemap.xml` and wants to be indexed.
   *
   * A dialog is not a page a stranger should arrive at cold, and a stub is not
   * a page at all — pointing a crawler at `/play/multiplayer`, which says "not
   * in this build", is asking to be indexed as the thing the project most
   * wants not to be mistaken for.
   */
  readonly index: boolean
}

/**
 * Longest path first, because `pageMetaFor` takes the first prefix that
 * matches and `/play/solo` has to win over `/`.
 */
export const PAGES: readonly PageMeta[] = [
  {
    path: PLANETARIUM,
    title: 'Planetarium',
    description:
      'Fly the real catalog. 7,123 systems and 702 known planets within 150 light years, derived rather than downloaded — no ship, no fuel, nowhere you cannot go.',
    index: true,
  },
  {
    path: CINEMA,
    title: 'Cinema',
    description:
      'Scripted scenes staged over the live simulation and played frame by frame. Every shot is the real world, seen from a camera on a script.',
    index: true,
  },
  {
    path: DOCS,
    title: 'Documentation',
    description:
      'How InertialRef works and why: the simulation, architecture decisions, design bible, and generated reference for every export of the engine.',
    index: true,
  },
  {
    path: ABOUT,
    title: 'About',
    description: `What ${SITE.name} is today — a pre-alpha architectural proof of a deterministic Milky Way — and where the astronomy and the source live.`,
    index: true,
  },
  {
    path: PLAY_SOLO,
    title: 'Solo Flight',
    description:
      'The whole simulation, offline. Nothing to download and nothing to ask a server for.',
    index: false,
  },
  {
    path: PLAY_ONLINE,
    title: 'Solo Online',
    description:
      'The same game, connected: discovery credit and sync across devices. Designed, not built.',
    index: false,
  },
  {
    path: PLAY_MULTIPLAYER,
    title: 'Multiplayer',
    description:
      'One shared, persistent galaxy. Deliberately deferred — see the roadmap.',
    index: false,
  },
  {
    path: SETTINGS,
    title: 'Settings',
    description:
      'Camera, display and simulation settings — the lens, antialiasing, HDR output and the flare, over whatever is running.',
    index: false,
  },
  {
    path: KEYS,
    title: 'Keyboard Controls',
    description:
      'The current keyboard controls for flight, the planetarium and cinema, including the shortcuts customized for this browser.',
    index: false,
  },
  ...[
    { path: PROFILE, title: 'Profile' },
    { path: SIGN_IN, title: 'Sign In' },
    { path: SIGN_UP, title: 'Sign Up' },
    { path: AUTH_CALLBACK, title: 'Account Callback' },
  ].map((page) => ({
    ...page,
    description:
      'Account features are planned for connected flight. Solo flight and the planetarium are available without an account.',
    index: false,
  })),
  {
    path: HOME,
    title: SITE.tagline,
    description: SITE.description,
    index: true,
  },
]

/** The home page is the final, least-specific entry. */
const ROOT = PAGES[PAGES.length - 1] as PageMeta

const missingPage = (path: string): PageMeta => ({
  path,
  title: 'Page Not Found',
  description:
    'This address has no page in InertialRef. Open the documentation or return to the home page to find your way around.',
  index: false,
})

/** Section defaults for routes whose deeper content supplies its own metadata. */
export function pageMetaFor(pathname: string): PageMeta {
  const path = withoutTrailingSlash(pathname)
  return (
    PAGES.find(
      (page) =>
        page.path !== HOME &&
        (path === page.path || path.startsWith(`${page.path}/`)),
    ) ?? (path === HOME ? ROOT : missingPage(path))
  )
}

/** Metadata for the exact HTML document, including a documentation article. */
export function metadataForPath(
  pathname: string,
  doc?: { readonly title: string; readonly lead: string } | null,
): PageMeta {
  const path = withoutTrailingSlash(pathname)
  const page = pageMetaFor(path)
  if (page.path === DOCS && path !== DOCS) {
    if (doc === null) return missingPage(path)
    if (doc !== undefined) {
      const lead = doc.lead.replace(/\s+/g, ' ').trim()
      const description =
        lead.length > 160
          ? `${lead.slice(0, 157).replace(/\s+\S*$/, '')}…`
          : lead || page.description
      return { path, title: doc.title, description, index: true }
    }
  }
  return { ...page, path }
}

export const robotsContent = (page: PageMeta): string =>
  page.index
    ? 'index, follow, max-image-preview:large, max-snippet:-1'
    : 'noindex, follow'

/**
 * What goes in `<title>`.
 *
 * The page first, the product second, separated by a middle dot rather than an
 * em dash: a tab strip truncates from the right, so the half that survives at
 * 120 px has to be the half that says where you are.
 */
export function documentTitle(page: PageMeta): string {
  return page.path === HOME
    ? `${SITE.name} — ${SITE.tagline}`
    : `${page.title} · ${SITE.name}`
}

/**
 * `/planetarium/` and `/planetarium` are one page, so they get one spelling.
 *
 * `/` is left alone — it is the only path where the slash is the path rather
 * than a separator with nothing after it.
 */
const withoutTrailingSlash = (pathname: string): string =>
  pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname

/** One canonical spelling per path, independent of a preview's hostname. */
export function canonicalUrl(pathname: string): string {
  const path = withoutTrailingSlash(pathname)
  return path === HOME ? SITE.origin : `${SITE.origin}${path}`
}
