import {
  ABOUT,
  CINEMA,
  DOCS,
  HOME,
  PLANETARIUM,
  PLAY_MULTIPLAYER,
  PLAY_ONLINE,
  PLAY_SOLO,
  SETTINGS,
} from './pages/paths.ts'

/*
 * Who this site says it is.
 *
 * One module, read by four things that would otherwise each carry their own
 * copy of the same sentence and drift:
 *
 * `pages/DocumentMeta.tsx`   the title, description and canonical link on
 *                            every navigation
 * `analytics.ts`             the one hostname that is allowed to be measured
 * `scripts/brand/build.mjs`  the share card, `robots.txt` and `sitemap.xml`
 * `astro/layouts/Base.astro` by hand, and only for the home page — see below
 *
 * **The layout is the exception and it is deliberate.** A social scraper does
 * not run JavaScript, so whatever this module computes at runtime is invisible
 * to the card Slack or iMessage draws. The static head is what those read, and
 * it is written for the home page because the SPA fallback still serves that
 * same document for every path. Keeping it in step is a hand job with a pointer
 * at both ends; the alternative is routing every navigation through the Worker
 * so `HTMLRewriter` can rewrite four tags, which turns a free static asset
 * request into a billed invocation on every page load. `docs/hosting.md`
 * records that trade as the seam to revisit if per-route cards ever matter
 * more than they do for a project with two shareable pages.
 *
 * Node runs this file directly (type stripping) so the build scripts can import
 * it. Nothing here may touch the DOM, React or `import.meta.env`.
 */

export const SITE = {
  name: 'InertialRef',
  /** The canonical host. Everything else — a preview, a `workers.dev`
   *  fallback, localhost — is the same build wearing a different name, and
   *  neither analytics nor a canonical link should treat it as this site. */
  host: 'inertialref.jonjaques.com',
  origin: 'https://inertialref.jonjaques.com',
  tagline: 'A real sky, in a browser tab',
  /**
   * The one sentence a stranger gets, and the length is the constraint.
   *
   * Search results truncate a description around 160 characters on desktop and
   * nearer 120 on mobile; this lands at 157, so the clause that ends it is a
   * clause somebody chose rather than wherever Google's ellipsis fell.
   * `site.test.ts` holds every page to that bound.
   */
  description:
    'An open-source spaceflight simulator in a browser tab. The Milky Way is the real one — 7,123 cataloged systems within 150 light years, the rest from a seed.',
  author: 'Jon Jaques',
  repository: 'https://github.com/jonjaques/inertialref',
  licence: 'Apache-2.0',
  /** Slate-950. The page behind the app, the icon plate and the share card all
   *  sit on it, and a browser paints it before the bundle arrives. */
  background: '#020617',
  /** 1200x630, generated by `pnpm brand`. */
  socialImage: '/og.png',
} as const

/* ------------------------------------------------------------------------- */
/* Pages                                                                      */
/* ------------------------------------------------------------------------- */

export interface PageMeta {
  /** The path this describes. Matched as a prefix, longest first. */
  readonly path: string
  /**
   * The page's own name, in title case and without the product's.
   *
   * `documentTitle` appends the product. Written here the way it is written
   * everywhere else in this interface — a label is read by a screen reader and
   * copied into a bookmark, and neither of those can undo a shout.
   */
  readonly title: string
  readonly description: string
  /**
   * Whether it belongs in `sitemap.xml` and wants to be indexed.
   *
   * A dialog is not a page a stranger should arrive at cold, and a stub is not
   * a page at all — pointing a crawler at `/play/multiplayer`, which says "not
   * in this build", is asking to be indexed as the thing the project most
   * wants not to be mistaken for.
   */
  readonly index: boolean
}

/**
 * Longest path first, because `pageMetaFor` takes the first prefix that
 * matches and `/play/solo` has to win over `/`.
 */
export const PAGES: readonly PageMeta[] = [
  {
    path: PLANETARIUM,
    title: 'Planetarium',
    description:
      'Fly the real catalog. 7,123 systems and 702 known planets within 150 light years, derived rather than downloaded — no ship, no fuel, nowhere you cannot go.',
    index: true,
  },
  {
    path: CINEMA,
    title: 'Cinema',
    description:
      'Scripted scenes staged over the live simulation and played frame by frame. Every shot is the real world, seen from a camera on a script.',
    index: true,
  },
  {
    path: DOCS,
    title: 'Documentation',
    description:
      'How InertialRef works and why: ten mechanisms, sixteen decision records, the design bible, and a generated reference for every export of the engine.',
    index: true,
  },
  {
    path: ABOUT,
    title: 'About',
    description: `What ${SITE.name} is today — a pre-alpha architectural proof of a deterministic Milky Way — and where the astronomy and the source live.`,
    index: true,
  },
  {
    path: PLAY_SOLO,
    title: 'Solo Flight',
    description:
      'The whole simulation, offline. Nothing to download and nothing to ask a server for.',
    index: false,
  },
  {
    path: PLAY_ONLINE,
    title: 'Solo Online',
    description:
      'The same game, connected: discovery credit and sync across devices. Designed, not built.',
    index: false,
  },
  {
    path: PLAY_MULTIPLAYER,
    title: 'Multiplayer',
    description:
      'One shared, persistent galaxy. Deliberately deferred — see the roadmap.',
    index: false,
  },
  {
    path: SETTINGS,
    title: 'Settings',
    description:
      'Camera, display and simulation settings — the lens, antialiasing, HDR output and the flare, over whatever is running.',
    index: false,
  },
  {
    path: HOME,
    title: SITE.tagline,
    description: SITE.description,
    index: true,
  },
]

/** The home page's entry, which is also the fallback for anything unlisted. */
const ROOT = PAGES[PAGES.length - 1] as PageMeta

/**
 * The metadata for a path, by longest matching prefix.
 *
 * A prefix rather than an exact match because the addressable surface is
 * deeper than the page list: `/cinema/tng-intro?t=1150` is the cinema page and
 * `/settings/camera` is the settings dialog. A scene deserving its own card is
 * a real thing to want and is not this — it needs the Worker, and the note at
 * the top of this file says why that is not free.
 */
export function pageMetaFor(pathname: string): PageMeta {
  const path = withoutTrailingSlash(pathname)
  return (
    PAGES.find(
      (page) =>
        page.path !== HOME &&
        (path === page.path || path.startsWith(`${page.path}/`)),
    ) ?? ROOT
  )
}

/**
 * What goes in `<title>`.
 *
 * The page first, the product second, separated by a middle dot rather than an
 * em dash: a tab strip truncates from the right, so the half that survives at
 * 120 px has to be the half that says where you are.
 */
export function documentTitle(page: PageMeta): string {
  return page.path === HOME
    ? `${SITE.name} — ${SITE.tagline}`
    : `${page.title} · ${SITE.name}`
}

/**
 * `/planetarium/` and `/planetarium` are one page, so they get one spelling.
 *
 * `/` is left alone — it is the only path where the slash is the path rather
 * than a separator with nothing after it.
 */
const withoutTrailingSlash = (pathname: string): string =>
  pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname

/**
 * The absolute URL for a path, for a canonical link or a sitemap entry.
 *
 * Normalized, and that is the whole reason this is a function rather than a
 * template literal at each call site. `pageMetaFor` already treats a trailing
 * slash as the same page and `sitemap.xml` lists the slash-less form — so a
 * visitor arriving at a shared `/planetarium/` link used to be served a
 * self-referencing canonical that disagreed with the sitemap. Two canonicals
 * for one page is the exact duplicate-content split the tag exists to prevent,
 * and it split the analytics `page_location` the same way.
 */
export function canonicalUrl(pathname: string): string {
  const path = withoutTrailingSlash(pathname)
  return path === HOME ? SITE.origin : `${SITE.origin}${path}`
}
