import { useState } from 'react'
import { PLATE_HEIGHT, PLATE_WIDTH, plateName } from '@inertialref/devtools'
import { FOCUS_RING, releaseFocus } from '../hud/focus.ts'

/**
 * One picture, with the frame it takes as its thumbnail.
 *
 * A plate rather than a drawing, and that is the whole difference between this
 * tier and the compositions under it. A composition is relative to whatever is
 * under the camera, so there is nothing particular to photograph and
 * `ShotThumb` draws the geometry the solver will use — a prediction. A picture
 * names an address, so the frame it produces is a specific thing the renderer
 * has already been asked for, and a diagram of a picture that exists is a worse
 * thumbnail than the picture.
 *
 * The plates are vendored under `apps/game/public/presets/` and regenerated by
 * `pnpm presets:plates`; `pnpm presets:check` proves every picture has one. A
 * capture that has gone missing falls back to the label alone rather than to a
 * broken-image glyph — the button still works, and the thing it does is not
 * about its own thumbnail.
 */
export function PictureCard({
  picture,
  onTake,
}: {
  readonly picture: {
    readonly id: string
    readonly label: string
    readonly why: string
  }
  readonly onTake: () => void
}) {
  const [missing, setMissing] = useState(false)
  return (
    <button
      type="button"
      title={picture.why}
      onClick={(event) => {
        releaseFocus(event)
        onTake()
      }}
      className={`group flex flex-col gap-1 rounded border border-slate-700/70 bg-slate-900/50 p-0.5 transition-[border-color,background-color,scale] hover:border-sky-500/60 hover:bg-slate-800/60 active:scale-[0.96] ${FOCUS_RING}`}
    >
      {missing ? (
        // The honest empty state: a frame the right shape with nothing in it,
        // rather than the browser's broken-image glyph, which reads as a fault
        // in the button rather than in a file that was never captured.
        <span className="flex aspect-3/2 w-full items-center justify-center rounded-sm bg-slate-950/60 text-slate-400">
          no plate
        </span>
      ) : (
        <img
          // Name and size from `pictures.ts`, which is what `presets:check`
          // gates and what `presets:plates` captures — a third copy here is a
          // format change that leaves the gate green and every card empty.
          src={`/presets/${plateName(picture.id)}`}
          alt=""
          width={PLATE_WIDTH}
          height={PLATE_HEIGHT}
          loading="lazy"
          onError={() => setMissing(true)}
          className="aspect-3/2 w-full rounded-sm object-cover"
        />
      )}
      <span className="type-label px-0.5 pb-0.5 text-center leading-tight text-balance text-slate-300 transition-colors group-hover:text-sky-200">
        {picture.label}
      </span>
    </button>
  )
}
